import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex justify-center items-center flex-col flex-1'>
       <h1>
        WordWolf
       </h1>
       <Link href='/play' className='bg-red-300 rounded-sm p-1'>Play!</Link>
      </div>
    </>
  )
}
